image:
  file: .gitpod.Dockerfile
ports:
    - name: VNC
      description: full GUI Virtual Desktop
      port: 6080
      onOpen: open-preview
    - port: 5900
      onOpen: ignore
    - port: 35900
      onOpen: ignore
tasks:
  - command: google-chrome --no-sandbox